### ISSUE TITLE
Port To STM32F407VG

### ISSUE THREAD

**Issue by Amitkor12** [sufst/vcu#232]
### Description
We have a dev board STM32F407VG, can we port this project on this board ?
If yes what are the specific areas we have to look upon.
What needs to be changed according to this hardware and software.

### Relevant FSUK Rules
we are developing a VCU for EV ATV.

### Additional Notes
initially we only want to control Throttle , Brake, Gear switch and reading of CAN messages from Motor Controller and BMS.

**Comment by brad-berry** [comment]
I have no experience with this board, however you should be able to use the SMT32CubeMX software to change the processor and it should work? Best of luck.
