### ISSUE TITLE
feat(can): configure CAN filter

### ISSUE THREAD

**Issue by hashyaha** [sufst/vcu#46]
- Configure STM32 to accept CAN messages from inverter with valid ID only.

**Comment by t-bre** [comment]
@hashyaha what is the status of this? Does it need to be done / would you have time to do it? I don't understand as much about it as you do!

**Comment by hashyaha** [comment]
The current configuration is to respond to all CAN id. It is not important as now we don't need to ignore/filter the CAN messages coming from different nodes.

**Comment by t-bre** [comment]
This is now the responsibility of the RTCAN module
