### ISSUE TITLE
Ready to drive sound

### ISSUE THREAD

**Issue by t-bre** [sufst/vcu#55]
- Speaker (12V @ 300ma) driven by FET.
- Output active high when entering ready-to-drive state for 1 to 3 seconds.

**Comment by t-bre** [comment]
Uses RTC, but only accurate to 1 second at the moment.

**Comment by lebedys** [comment]
FSUK Rules (2022 v1.0):

**EV 4.12.1** The vehicle must make a characteristic sound, continuously for at least one second and a
maximum of three seconds when it enters ready-to-drive mode.

**EV 4.12.2** The sound level must be a minimum of 80 dBA and a maximum of 90 dBA, fast weighting
in a radius of 2 m around the vehicle.

**EV 4.12.3** The used sound must be easily recognizable. No animal voices, song parts or sounds that
could be interpreted as offensive will be accepted.

**EV 4.12.4** The vehicle must not make any other sounds similar to the ready-to-drive sound.
