### ISSUE TITLE
feat(can): inverter commands in fault state

### ISSUE THREAD

**Issue by t-bre** [sufst/vcu#58]
### Description
In the event of a critical fault, the inverter should produce zero torque and be put in a safe state.

### Specification

- [x] Set the CAN timeout for the inverter (via RMS GUI).
- [x] Transmit inverter disable command.
- [x] Drive inverter enable pin low.

### Relevant competition rules
See #54.

### Additional context
In the event of a critical fault the RTOS enters a fault thread and terminates all other threads (including the CAN thread).
See #54 for more.

**Comment by t-bre** [comment]
@hashyaha it might be good if you can create a special zero torque CAN message which is pre-constructed at compile time. It would also be good to have a function like `request_zero_torque()` which can be called from the fault state thread to make things as simple as possible to integrate.

**Comment by hashyaha** [comment]
> * We need a mechanism to immediately send a torque request of zero independently of the CAN thread (hopefully we can just call one of the functions @hashyaha is implementing for inverter communications).

@t-bre The inverter has a CAN timeout feature (see pg. 8 of CAN protocol) which will generate a fault and stop the motor if the "heartbeat" torque command message is not received by inverter before CAN timeout time expires. 
In this case, is it good enough in terms of reaction time if we enable inverter's CAN timeout feature and stop transmitting CAN command in the critical fault thread? 
_The CAN timeout parameter is set as a multiple of 3 msec._
[CAN Protocol (V5_9).pdf](https://github.com/sufst/vcu/files/8257711/CAN.Protocol.V5_9.pdf)

**Comment by t-bre** [comment]
@hashyaha that sounds perfect, nice and simple as a solution. I'm not entirely sure what the required response time is, but if we could have some kind of configurable thing like:
```C
#define INVERTER_TIMEOUT  100 // in ms
``` 
Then on initialisation, we send the configuration to the inverter specifying this timeout. This value would be defined in the [configuration header](https://github.com/sufst/vcu/blob/main/embedded/SUFST/Inc/config.h) which I think is new since your branch was created (maybe a sign its time to do some merging and integration in the next meeting).

@lebedys do you have any details on the required timeout / response time?

**Comment by t-bre** [comment]
@hashyaha can you link the inverter / CAN datasheets on the README on [this branch](https://github.com/sufst/vcu/tree/docs/initial-documentation) if you have online links to them for quick access.

Also if you have any useful notes to make on how the CAN / inverter works in the VCU it would be good to add it to the new wiki which we are working on!
