### ISSUE TITLE
Conflicting GPIO pin PB14

### ISSUE THREAD

**Issue by t-bre** [sufst/vcu#88]
### Description
`CAN_Rx()` in `can_types.c` writes to GPIOB pin 14. This pin is already assigned to the built-in red status LED.

### Expected behaviour
Different pins should be used to avoid conflict. 
Use yellow built-in LED for CAN debug.

### Additional context
Start of `CAN_Rx()` function:

```C
void CAN_Rx()
{
    FDCAN_RxHeaderTypeDef RxHeader;
    uint8_t	RxData[8];

    queue_msg_t Rx_msg;
    HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_14);

    // ...
```
Conflicting lines in `main.h`:
```C
#define RED_LED_Pin GPIO_PIN_14
#define RED_LED_GPIO_Port GPIOB
```

**Comment by t-bre** [comment]
@hashyaha do you known the purpose of the `HAL_GPIO_TogglePin()` call here? Is it related to CAN functionality or is it intentionally toggling the LED for each CAN transmission?

**Comment by hashyaha** [comment]
Yea, you're right, I was using it as debug LED. It should be removed.

**Comment by t-bre** [comment]
Great thank you, I'll do that 👍

**Comment by t-bre** [comment]
Is it still useful to have a debug LED? I could move it to the yellow LED which is unused?

**Comment by hashyaha** [comment]
That would be great :)
